# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

env:
  shell: bash
  parameter-store:
    GITHUB_ACCESS_TOKEN: GITHUB_ACCESS_TOKEN
    NEXUS_REPO_PASSWORD: NEXUS_REPO_PASSWORD

phases:

  install:
    runtime-versions:
      java: openjdk8
    commands:
    - mkdir -p /root/.ivy2/cache
    - java -version
    - |
        echo "realm=Sonatype Nexus Repository Manager
        host=nexus.timeout.com
        user=deployment" > /root/.ivy2/.credentials
    - echo "password=$NEXUS_REPO_PASSWORD" >> /root/.ivy2/.credentials

  pre_build:
    commands:
    - git clone https://${GITHUB_ACCESS_TOKEN}@github.com/timeoutdigital/akka-http-healthchecks.git
    - cd akka-http-healthchecks
    - TAG=$(git describe --abbrev=0 --match "[0-9]\.[0-9]*" --tags)
    - echo $TAG
    - echo $TAG | grep -E "^[[:digit:]]+?\.[[:digit:]]+?$" && echo "Release Tag O.K." || (echo "Invalid Tag Format" && exit 1)
    - git checkout $TAG
    - git rev-parse HEAD

  build:
    commands:
    - TAG=$(git describe --abbrev=0 --match "[0-9]\.[0-9]*" --tags)
    - echo "about to release akka-http-healthchecks $TAG"
    - java -Dsbt.log.noformat=true -jar /usr/local/bin/sbt/bin/sbt-launch.jar "release with-defaults default-tag-exists-answer o release-version $TAG"
